name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build and Push to Docker
      run: |
        docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker build . --tag shockerovip/qim-server_dockerized-v2:latest
        docker push shockerovip/qim-server_dockerized-v2:latest
      #repository: ${{ github.repository }}
      #tag_with_ref: true
      #tag_with_sha: true
      #tags: ${{ github.sha }}
    
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    #  run: |
    #    docker build -t username/repo-client:latest ./client
    #   docker push username/repo-client:latest
